version: '3'
services:
  airflow-cli:
    image: ${SELFMADE_AIRFLOW_IMAGE}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    command:
      - bash
      - -c
      - airflow dags trigger load_variables_dag -r varsrescan

